/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projek.pribadi;

import javax.swing.JOptionPane;

/**
 *
 * @author Mic
 */
public class index extends javax.swing.JFrame {
    
    

    /**
     * Creates new form index
     */
    public index() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        rkubus = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        bvkubus = new javax.swing.JButton();
        blkubus = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        blbalok = new javax.swing.JButton();
        pbalok = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        bvbalok = new javax.swing.JButton();
        lbalok = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tbalok = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        rbola = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        bvbola = new javax.swing.JButton();
        blbola = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        rtabung = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        bvtabung = new javax.swing.JButton();
        bltabung = new javax.swing.JButton();
        ttabung = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        rkerucut = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        bvkerucut = new javax.swing.JButton();
        blkerucut = new javax.swing.JButton();
        tkerucut = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        smkerucut = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane2.setBackground(new java.awt.Color(204, 51, 0));
        jTabbedPane2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rkubus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rkubusActionPerformed(evt);
            }
        });
        jPanel1.add(rkubus, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 11, 107, -1));

        jLabel1.setText("Panjang rusuk");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, -1, -1));

        bvkubus.setText("Volume");
        bvkubus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bvkubusActionPerformed(evt);
            }
        });
        jPanel1.add(bvkubus, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 42, 193, 45));

        blkubus.setText("Luas Permukaan");
        blkubus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blkubusActionPerformed(evt);
            }
        });
        jPanel1.add(blkubus, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 98, 193, 45));

        jTabbedPane2.addTab("Kubus", jPanel1);

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));

        blbalok.setText("Luas Permukaan");
        blbalok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blbalokActionPerformed(evt);
            }
        });

        pbalok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pbalokActionPerformed(evt);
            }
        });

        jLabel2.setText("Panjang");

        bvbalok.setText("Volume");
        bvbalok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bvbalokActionPerformed(evt);
            }
        });

        lbalok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbalokActionPerformed(evt);
            }
        });

        jLabel3.setText("Lebar");

        tbalok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbalokActionPerformed(evt);
            }
        });

        jLabel5.setText("Tinggi");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(bvbalok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(blbalok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbalok, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pbalok, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tbalok, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel5))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pbalok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbalok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbalok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bvbalok, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(blbalok, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Balok", jPanel2);

        jPanel3.setBackground(new java.awt.Color(204, 51, 255));

        rbola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbolaActionPerformed(evt);
            }
        });

        jLabel4.setText("Jari - jari");

        bvbola.setText("Volume");
        bvbola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bvbolaActionPerformed(evt);
            }
        });

        blbola.setText("Luas Permukaan");
        blbola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blbolaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rbola, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bvbola, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blbola, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rbola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(bvbola, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(blbola, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Bola", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 51, 51));

        rtabung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rtabungActionPerformed(evt);
            }
        });

        jLabel6.setText("Jari - jari");

        bvtabung.setText("Volume");
        bvtabung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bvtabungActionPerformed(evt);
            }
        });

        bltabung.setText("Luas Permukaan");
        bltabung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bltabungActionPerformed(evt);
            }
        });

        ttabung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ttabungActionPerformed(evt);
            }
        });

        jLabel7.setText("Tinggi");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rtabung, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bvtabung, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bltabung, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ttabung, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(rtabung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ttabung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bvtabung, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(bltabung, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Tabung", jPanel4);

        jPanel5.setBackground(new java.awt.Color(204, 255, 51));

        rkerucut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rkerucutActionPerformed(evt);
            }
        });

        jLabel8.setText("Jari - jari");

        bvkerucut.setText("Volume");
        bvkerucut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bvkerucutActionPerformed(evt);
            }
        });

        blkerucut.setText("Luas Permukaan");
        blkerucut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blkerucutActionPerformed(evt);
            }
        });

        tkerucut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tkerucutActionPerformed(evt);
            }
        });

        jLabel9.setText("Tinggi");

        smkerucut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smkerucutActionPerformed(evt);
            }
        });

        jLabel10.setText("Sisi Miring *");

        jLabel11.setText("* Khusus Luas Permukaan");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rkerucut, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(bvkerucut, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(blkerucut, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tkerucut, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(smkerucut, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel11))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(rkerucut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tkerucut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(smkerucut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(bvkerucut, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(blkerucut, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Kerucut", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void smkerucutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smkerucutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_smkerucutActionPerformed

    private void tkerucutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tkerucutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tkerucutActionPerformed

    private void rkerucutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rkerucutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rkerucutActionPerformed

    private void ttabungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ttabungActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ttabungActionPerformed

    private void rtabungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rtabungActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rtabungActionPerformed

    private void rbolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbolaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbolaActionPerformed

    private void tbalokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbalokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbalokActionPerformed

    private void lbalokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbalokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbalokActionPerformed

    private void pbalokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pbalokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pbalokActionPerformed

    private void rkubusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rkubusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rkubusActionPerformed

    private void bvkubusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bvkubusActionPerformed
        int r = Integer.parseInt(rkubus.getText().toString());        
        int v = r*r*r ;        
        JOptionPane.showMessageDialog(null,"Volume =  "+v);
        

    // TODO add your handling code here:
    }//GEN-LAST:event_bvkubusActionPerformed

    private void blkubusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blkubusActionPerformed
        int r = Integer.parseInt(rkubus.getText().toString());        
        int lp = r*r*6 ;        
        JOptionPane.showMessageDialog(null,"Luas Permukaan =  "+lp);
        // TODO add your handling code here:
    }//GEN-LAST:event_blkubusActionPerformed

    private void bvbalokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bvbalokActionPerformed
        int p = Integer.parseInt(pbalok.getText().toString());
        int l = Integer.parseInt(lbalok.getText().toString());
        int t = Integer.parseInt(tbalok.getText().toString());
        int v = p*l*t ;        
        JOptionPane.showMessageDialog(null,"Volume =  "+v);
        // TODO add your handling code here:
    }//GEN-LAST:event_bvbalokActionPerformed

    private void blbalokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blbalokActionPerformed
        int p = Integer.parseInt(pbalok.getText().toString());
        int l = Integer.parseInt(lbalok.getText().toString());
        int t = Integer.parseInt(tbalok.getText().toString());
        int v = 2*((p*l)+(l*t)+(t*p)) ;        
        JOptionPane.showMessageDialog(null,"Luas Permukaan =  "+v);
            // TODO add your handling code here:
    }//GEN-LAST:event_blbalokActionPerformed

    private void bvbolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bvbolaActionPerformed
        int r = Integer.parseInt(rbola.getText().toString());
        Double v = (4/3.0*22/7)*r*r*r ;        
        JOptionPane.showMessageDialog(null,"Volume =  "+v);
        // TODO add your handling code here:
    }//GEN-LAST:event_bvbolaActionPerformed

    private void blbolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blbolaActionPerformed
        int r = Integer.parseInt(rbola.getText().toString());
        Double v = (4.0*22/7)*r*r ;        
        JOptionPane.showMessageDialog(null,"Luas Permukaan =  "+v);
        // TODO add your handling code here:
    }//GEN-LAST:event_blbolaActionPerformed

    private void bvtabungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bvtabungActionPerformed
        int r = Integer.parseInt(rtabung.getText().toString());
        int t = Integer.parseInt(ttabung.getText().toString());
        Double v = (22/7.0*r*r)*t ;        
        JOptionPane.showMessageDialog(null,"Volume =  "+v);
        // TODO add your handling code here:
    }//GEN-LAST:event_bvtabungActionPerformed

    private void bltabungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bltabungActionPerformed
        int r = Integer.parseInt(rtabung.getText().toString());
        int t = Integer.parseInt(ttabung.getText().toString());
        Double v = (2.0*22/7*r*r)+(22/7.0*(2*r)*t) ;
        JOptionPane.showMessageDialog(null,"Luas Permukaan =  "+v);
        // TODO add your handling code here:
    }//GEN-LAST:event_bltabungActionPerformed

    private void bvkerucutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bvkerucutActionPerformed
        int r = Integer.parseInt(rkerucut.getText().toString());
        int t = Integer.parseInt(tkerucut.getText().toString());
        
        Double v = 1/3.0*22/7*r*r*t ;
        JOptionPane.showMessageDialog(null,"Volume =  "+v);
        // TODO add your handling code here:
    }//GEN-LAST:event_bvkerucutActionPerformed

    private void blkerucutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blkerucutActionPerformed
        int r = Integer.parseInt(rkerucut.getText().toString());
        int t = Integer.parseInt(tkerucut.getText().toString());
        int sm = Integer.parseInt(smkerucut.getText().toString());
        Double v = (3/4.0*22/7*sm)+(22/7*r*r) ;
        JOptionPane.showMessageDialog(null,"Luas Permukaan =  "+v);
// TODO add your handling code here:
    }//GEN-LAST:event_blkerucutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton blbalok;
    private javax.swing.JButton blbola;
    private javax.swing.JButton blkerucut;
    private javax.swing.JButton blkubus;
    private javax.swing.JButton bltabung;
    private javax.swing.JButton bvbalok;
    private javax.swing.JButton bvbola;
    private javax.swing.JButton bvkerucut;
    private javax.swing.JButton bvkubus;
    private javax.swing.JButton bvtabung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField lbalok;
    private javax.swing.JTextField pbalok;
    private javax.swing.JTextField rbola;
    private javax.swing.JTextField rkerucut;
    private javax.swing.JTextField rkubus;
    private javax.swing.JTextField rtabung;
    private javax.swing.JTextField smkerucut;
    private javax.swing.JTextField tbalok;
    private javax.swing.JTextField tkerucut;
    private javax.swing.JTextField ttabung;
    // End of variables declaration//GEN-END:variables
}
